# Generated by Django 5.1.2 on 2024-10-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_category_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="subcategory",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="subcategories",
            field=models.ManyToManyField(
                related_name="menu_items", to="payments.subcategory"
            ),
        ),
    ]
