# Generated by Django 5.1.2 on 2024-10-24 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_remove_menuitem_subcategory_menuitem_subcategories"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="subcategories",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="subcategory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="payments.subcategory",
            ),
        ),
    ]
