# Generated by Django 5.1.2 on 2024-10-26 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0009_alter_menuitem_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_id",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
