# Generated by Django 5.1.2 on 2024-10-28 13:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0010_alter_order_order_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="payments.client",
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
