# Generated by Django 5.1.2 on 2024-10-28 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0011_order_client_alter_client_birthday"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="client_email",
        ),
        migrations.RemoveField(
            model_name="order",
            name="client_name",
        ),
    ]
