# Generated by Django 5.1.2 on 2024-11-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_remove_order_client_email_remove_order_client_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_pt",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="name_pt",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
